### ISSUE TITLE
toDynamoDBConditionExpression missing on "@aws-appsync/utils": "^1.5.0"

### ISSUE THREAD

**Issue by BerndWessels** [localstack/appsync-utils#8]
Hello

I'm a bit desperate and ended up here.
 
I want to use `toDynamoDBConditionExpression` with `@aws-appsync/utils` in my JavaScript appsync resolvers.
But turns out that `@aws-appsync/utils` does not even have the `transform` property, even though it is documented here `https://docs.aws.amazon.com/appsync/latest/devguide/transformation-helpers-in-utils-transform-js.html`

Can you please let me know what am I missing and how to be able to use `toDynamoDBConditionExpression` in my resolvers?

Thank you so much @simonrw

**Comment by simonrw** [comment]
Hi @BerndWessels, thanks for raising this issue. We have implemented `toDynamoDBConditionExpression` in #3. In order to use the latest utils package in LocalStack, you must run LocalStack with the configuration:

```
APPSYNC_JS_LIBS_VERSION=refresh
```

This will download the latest version. I am going to close this issue, but if you still experience issues, please feel free to re-open or open another issue.
